Adds a dashboard
chacaa/DayDreaming pull request #25
Opened 2017-04-03 20:50 UTC by chacaa

Adds the dashboard view to the app.

### Related cards:
* [Dashboard Logic](https://github.com/chacaa/DD/issues/5)
* [Dashboard View](https://github.com/chacaa/DD/issues/4)

### UI preview:
![UI](http://g.recordit.co/CjF437MfSY.gif)

/cc @xmartlabs/android

2017-04-04 11:15 UTC, bryant1410 requested changes

2017-04-04 11:15 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/dd/helper/SystemServiceHelper.java
>  }
leave newline here

2017-04-04 11:15 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +@SuppressWarnings("deprecation")
? Is dangerous to apply this at a class level. You might be missing something if you do this.

2017-04-04 11:15 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +    layoutParams.setMargins(0, (-1) * marginTopInPx, 0, 0);
`- marginTopInPx`?

2017-04-04 11:15 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +    float heightInPx = view.getMeasuredHeight();
What about marking this var with a px-related annotation?

2017-04-04 11:15 UTC, bryant1410 commented on app/src/main/res/layout/dashboard_fragment.xml
> +        <ImageView
This isn't the way to add the hamburger icon. Check out the `navigationIcon` attribute from Toolbar.

2017-04-04 11:15 UTC, bryant1410 commented on app/src/main/res/layout/dashboard_fragment.xml
> +                    android:textColor="@color/warm_grey"
Consider defining styles to refactor common attributes.

2017-04-04 11:15 UTC, bryant1410 commented on app/src/main/res/layout/dashboard_fragment.xml
> +    <android.support.v7.widget.Toolbar
Are you sure to use the toolbar in the fragment?

2017-04-04 11:15 UTC, bryant1410 commented on app/src/main/res/layout/dashboard_fragment.xml
> +        <com.github.florent37.diagonallayout.DiagonalLayout
So, are the items fixed? Or can they change dynamically?

2017-04-04 11:15 UTC, bryant1410 commented on app/src/main/res/values/strings.xml
> +    <string name="home_custom">CUSTOM</string>
Consider using the TextView attribute `textAllCaps` instead of using uppercase here.

2017-04-04 14:32 UTC, chacaa commented on app/src/main/res/layout/dashboard_fragment.xml
> +        <com.github.florent37.diagonallayout.DiagonalLayout
Yep, they are fixed.

2017-04-04 14:35 UTC, mirland requested changes

2017-04-04 14:35 UTC, mirland commented on app/src/androidTest/java/com/xmartlabs/dd/ui/common/BaseInstrumentationTest.java
> +    DDApplication app = (DDApplication) instrumentation.getTargetContext().getApplicationContext();
shouldn't be `Dd...`?

2017-04-04 14:35 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +  private static final int ANIMATION_DURATION = 300;
put the unit in the name

2017-04-04 14:35 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +    int marginTopInPx = optionHeightInPx / 4;
why 4? 3 +1? you shouldn't use magic numbers

2017-04-04 14:35 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +    setUpDiagonalLayoutView(customView, optionHeightInPx, 0);
you can use a list of views and avoid the usage of `QUANTITY_OF_OPTIONS`

2017-04-04 14:35 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +    ValueAnimator animator = ValueAnimator.ofInt(params.bottomMargin, 25);//TODO calculate the value dynamically
add a space between the comment

2017-04-04 14:35 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/StartActivity.java
>      intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
chain the calls

2017-04-04 14:35 UTC, matir91 commented on app/src/main/res/layout/dashboard_fragment.xml
> +    <LinearLayout
in my opinion you should use an enum with the options and then the option should be added dynamically. BTW it could be a future improvement

2017-04-04 14:38 UTC, diegomedina248 requested changes

2017-04-04 14:38 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardActivity.java
> +    return new DashboardFragment();
Maybe use `FragmentWithArgs` and the builder mode as we do now

2017-04-04 14:38 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +  @BindView(R.id.bottom_black)
This is kind of repetitive. Can we at least extract this to a different view?
(it would be even better to use a recyclerview)

2017-04-04 14:38 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +    //TODO calculate margintop = width * tan(7)
why is this here?

2017-04-04 14:38 UTC, diegomedina248 commented on app/src/main/res/layout/dashboard_fragment.xml
> +        <com.github.florent37.diagonallayout.DiagonalLayout
Still thinking this should at least belong in it's on view

2017-04-04 14:38 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +  protected int getLayoutResId() {
@LayoutRes

2017-04-04 14:39 UTC, chacaa commented on app/src/androidTest/java/com/xmartlabs/dd/ui/common/BaseInstrumentationTest.java
> +    DDApplication app = (DDApplication) instrumentation.getTargetContext().getApplicationContext();
No, because the application name is Day Dreaming so the short term is DD.

2017-04-05 14:52 UTC, mirland requested changes

2017-04-05 14:52 UTC, matir91 commented on app/src/androidTest/java/com/xmartlabs/dd/ui/common/BaseInstrumentationTest.java
> +    DDApplication app = (DDApplication) instrumentation.getTargetContext().getApplicationContext();
But DD is a acronym, for example uri is an acronym to and the right name is Uri. Maybe you should use `DayDreaming` in the whole project. Why are you using `DD`?

2017-04-05 14:52 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/helper/SystemServiceHelper.java
>  }
Add space

2017-04-05 14:52 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +  private static final int BLACK_LINE_HEIGHT_IN_PX = MetricsHelper.dpToPxInt(10);
Add px annotation

2017-04-05 14:52 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +  protected int getLayoutResId() {
LayoutRes

2017-04-05 14:52 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +  //TODO change the animation, i left this here to use it later
the comment should not be personal

2017-04-05 14:52 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/DiagonalLayoutView.java
> +    TypedArray typedArray = getContext().obtainStyledAttributes(attrs, R.styleable.DiagonalLayoutView);
split in functions!

2017-04-05 14:52 UTC, matir91 commented on app/src/main/java/com/xmartlabs/dd/ui/StartActivity.java
>      intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
Fix the comment

2017-04-05 14:52 UTC, matir91 commented on app/src/main/res/layout/dashboard_fragment.xml
> +    android:id="@+id/menu"
it's strange having an id here

2017-04-05 14:52 UTC, matir91 commented on app/src/main/res/layout/dashboard_fragment.xml
> +    <com.xmartlabs.dd.ui.DiagonalLayoutView
cool :)

2017-04-05 14:59 UTC, diegomedina248 commented on app/src/androidTest/java/com/xmartlabs/dd/ui/common/BaseInstrumentationTest.java
> +    DDApplication app = (DDApplication) instrumentation.getTargetContext().getApplicationContext();
Or Dd according to the style guide, but it's sounds and looks ugly

2017-04-05 15:00 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +  private static final int BLACK_LINE_HEIGHT_IN_PX = MetricsHelper.dpToPxInt(10);
And remove IN_PX suffix

2017-04-05 15:03 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +      int heightInPx = view.getMeasuredHeight() - (2 * BLACK_LINE_HEIGHT_IN_PX);
I'd remove the InPx now.

2017-04-05 15:05 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +      setUpDiagonalLayoutView(customView, optionHeightInPx, 0);
Why are you setting up six views? Aren't there just three?

2017-04-05 15:07 UTC, chacaa commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +      setUpDiagonalLayoutView(customView, optionHeightInPx, 0);
Because I added two views to create the separations as shown in the App's design.

2017-04-05 15:08 UTC, chacaa commented on app/src/main/java/com/xmartlabs/dd/ui/DashboardFragment.java
> +      setUpDiagonalLayoutView(customView, optionHeightInPx, 0);
And the last one is necessary for making the diagonal line of the last item of the dashboard.

2017-04-05 17:00 UTC, diegomedina248 approved these changes

2017-04-05 17:49 UTC, mirland approved these changes
Fix comments

2017-04-05 17:49 UTC, matir91 commented on app/src/main/java/com/xmartlabs/daydreaming/helper/DateHelper.java
> +  private static final String DATE_COMPLETE = "yyyy-MMM-DayDreaming HH:mm:ss";
be careful

2017-04-05 17:49 UTC, matir91 commented on app/src/main/java/com/xmartlabs/daydreaming/helper/DateHelper.java
> +  public static final String DATE_ISO_8601 = "yyyy-MM-DayDreaming'T'HH:mm:ss.SSS'Z'";
too

2017-04-05 17:49 UTC, matir91 commented on app/src/main/java/com/xmartlabs/daydreaming/ui/DashboardFragment.java
> +  //TODO change the animation. It will be used later.
impersonal

2017-04-05 17:49 UTC, matir91 commented on app/src/main/java/com/xmartlabs/daydreaming/ui/DiagonalLayoutView.java
> +    TypedArray typedArray = getContext().obtainStyledAttributes(attrs, R.styleable.DiagonalLayoutView);
this should be inside the function

2017-04-05 19:45 UTC, chacaa commented on app/src/main/java/com/xmartlabs/daydreaming/ui/DashboardFragment.java
> +  //TODO change the animation. It will be used later.
Done!

2017-04-05 19:54 UTC, michaelEllisUy approved these changes

2017-04-05 19:57 UTC, bryant1410 approved these changes

2017-04-05 20:23 UTC, merged