Adds Custom Screen.
chacaa/DayDreaming pull request #31
Opened 2017-04-10 18:03 UTC by chacaa

Adds the feature to specify a custom video playlist.

### Related Github Project cards:
* [Custom screen view](https://github.com/chacaa/DayDreaming/issues/8) (resolves #8) 
* [Custom screen logic](https://github.com/chacaa/DayDreaming/issues/9) (resolves #9)

### UI preview:
![UI](http://g.recordit.co/o3jzP0tsen.gif)

/cc @xmartlabs/android

2017-04-10 19:00 UTC, diegomedina248 requested changes

2017-04-10 19:00 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/daydreaming/ui/CustomScreenFragment.java
> +    //TODO do something with that
These TODO are still needed?

2017-04-10 19:00 UTC, diegomedina248 commented on app/src/main/res/drawable/double_square_shape_2.xml
> +</layer-list>
End line

2017-04-10 19:00 UTC, diegomedina248 commented on app/src/main/res/drawable/double_square_shape_2_selected.xml
> +</layer-list>
Same here

2017-04-10 19:00 UTC, diegomedina248 commented on app/src/main/res/drawable/double_square_shape_2_selected.xml
> +</layer-list>
And review all files

2017-04-10 19:00 UTC, diegomedina248 commented on app/src/main/res/drawable/thumb.xml
> +
Remove these spaces

2017-04-10 19:17 UTC, chacaa commented on app/src/main/java/com/xmartlabs/daydreaming/ui/CustomScreenFragment.java
> +    //TODO do something with that
yep, because I'll have to use that info in order to configure the video.

2017-04-10 19:28 UTC, diegomedina248 approved these changes

2017-04-11 11:38 UTC, bryant1410 approved these changes

2017-04-11 11:38 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/daydreaming/ui/AboutScreenActivity.java
> + * Created by santiago on 4/10/17.
you're "chaca" man! not santiago :smile:

I hit first

2017-04-11 11:38 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/daydreaming/ui/CustomScreenFragment.java
> +  private int getColor(@ColorRes int color) {
This could go in the base fragment

2017-04-11 11:38 UTC, bryant1410 commented on app/src/main/res/values/strings.xml
>      <string name="rate">RATE APP</string>
Avoid these uppercase texts

2017-04-11 11:38 UTC, bryant1410 commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/warm_grey</item>
alpha

2017-04-11 14:27 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/daydreaming/ui/AboutScreenActivity.java
> + * Created by santiago on 4/10/17.
but you're not Android anymore, so you don't get a vote

2017-04-11 14:43 UTC, michaelEllisUy requested changes

2017-04-11 14:43 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/CustomScreenFragment.java
> +    //TODO do something with that
do something with what? Be more explicit about the todo. What is there to do?

2017-04-11 14:43 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/CustomScreenFragment.java
> +    //TODO do something with that
do something with what? Be more explicit about the todo. What is there to do?

2017-04-11 14:43 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/CustomScreenFragment.java
> +    //TODO do something with that
do something with what? Be more explicit about the todo. What is there to do?

2017-04-11 14:43 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/CustomScreenFragment.java
> +    //TODO do something with that
do something with what? Be more explicit about the todo. What is there to do?

2017-04-11 14:43 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/CustomScreenFragment.java
> +    //TODO do something with that
do something with what? Be more explicit about the todo. What is there to do?

2017-04-11 14:43 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/CustomScreenFragment.java
> +  private int getColor(@ColorRes int color) {
Or in some kind of helper/utils

2017-04-11 14:45 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/AboutScreenActivity.java
> + * Created by santiago on 4/10/17.
@bryant1410, i think @diegomedina248 is crossing his line here. "I throw it"

2017-04-11 14:46 UTC, chacaa commented on app/src/main/res/values/strings.xml
>      <string name="rate">RATE APP</string>
Yep, but i don't have the `textAllCaps` because in the navigation view, in which I use it, I don't have that property.

2017-04-11 14:51 UTC, chacaa commented on app/src/main/java/com/xmartlabs/daydreaming/ui/AboutScreenActivity.java
> + * Created by santiago on 4/10/17.
Yep, my bad! hahaha I forgot to change it in my computer..

2017-04-11 14:52 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/daydreaming/ui/AboutScreenActivity.java
> + * Created by santiago on 4/10/17.
It's just one screw up after another..

2017-04-11 15:15 UTC, bryant1410 commented on app/src/main/res/values/strings.xml
>      <string name="rate">RATE APP</string>
don't understand man. What do you mean?

2017-04-11 15:27 UTC, chacaa commented on app/src/main/res/values/strings.xml
>      <string name="rate">RATE APP</string>
What I meant is that the string "RATE APP" I use it as an option of a menu, and when I write the xml of that menu I don't have the property that I mentioned above, so in order to use the string in that way I have to write all in caps in the string.xml file.

2017-04-11 17:52 UTC, michaelEllisUy approved these changes

2017-04-11 17:53 UTC, merged