Adds login and register view
chacaa/DayDreaming pull request #33
Opened 2017-04-13 16:03 UTC by chacaa

Adds a login and register view to the app, also the logic necessary for that.

### Related Trello cards:
* [Login/Register view](https://github.com/chacaa/DayDreaming/issues/13) (resolves #13)
* [Login logic](https://github.com/chacaa/DayDreaming/issues/15)
* [Register logic](https://github.com/chacaa/DayDreaming/issues/14) (resolves #14)

### UI preview:
![UI](http://g.recordit.co/pDF372rBtD.gif)

/cc @xmartlabs/android

2017-04-13 16:15 UTC, bryant1410 approved these changes

2017-04-13 16:24 UTC, diegomedina248 approved these changes

2017-04-13 16:24 UTC, diegomedina248 commented on app/src/main/res/layout/login_register_fragment.xml
> +</RelativeLayout>
end line

2017-04-13 16:24 UTC, diegomedina248 commented on app/src/main/res/values/strings.xml
> +    <string name="error_hint">Password must be 6 digit long, at least 1 caps, 1 number</string>
I'd rename it to error_hint_sign_up, as this error is not generic

2017-04-13 22:05 UTC, michaelEllisUy requested changes

2017-04-13 22:05 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/LoginRegisterFragment.java
> +        errorTextView.setText("Wrong user account");
Make this a resource

2017-04-13 22:05 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/LoginRegisterFragment.java
> +      if (!(usernameFieldView.getText().toString().toLowerCase()).equals("santi")){
Add a TODO to replace this when you have access to a db to check if the user is registered?

2017-04-13 22:05 UTC, michaelEllisUy commented on app/src/main/res/layout/login_register_fragment.xml
> +                        android:id="@+id/username_field"
You could have aligned it with the start of the username_error imageview. 

I know that the image won't be shown until it shows an error, but when it does, will this be shown above the EditText?

Setting big margins for this is like cheating :P 
You could just set the imageView state to `hidden`, not `gone` and that's it.

Adding the cross to the `error_text_view` as a startDrawable, would've been an alternative, which would have saved lines. (Obviously, this is without taking design desitions into account)

Same thing applies for other layouts

For example:

        <ImageView
            android:id="@+id/holy_canoli"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:background="@color/blueDark"
            android:layout_alignParentEnd="true"
            android:src="@drawable/alerts_tutorial_bf"
            />

        <EditText
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:background="@color/cpb_red"
            android:layout_alignParentStart="true"
            android:layout_toStartOf="@id/holy_canoli"
            />

2017-04-13 22:05 UTC, michaelEllisUy commented on app/src/main/res/layout/login_register_fragment.xml
> +                        android:id="@+id/password_field"
same here

2017-04-14 16:02 UTC, diegomedina248 commented on app/src/main/res/layout/login_register_fragment.xml
> +                        android:id="@+id/username_field"
Totally agree.
Btw, i think the property is `invisible`, not `hidden`

2017-04-14 17:12 UTC, chacaa commented on app/src/main/java/com/xmartlabs/daydreaming/ui/LoginRegisterFragment.java
> +        errorTextView.setText("Wrong user account");
I didn't make this a resource because I use it for testing only and it won't be there in the final version.

2017-04-14 17:13 UTC, chacaa commented on app/src/main/res/layout/login_register_fragment.xml
> +                        android:id="@+id/username_field"
I'll do what we talk

2017-04-14 17:13 UTC, chacaa commented on app/src/main/java/com/xmartlabs/daydreaming/ui/LoginRegisterFragment.java
> +      if (!(usernameFieldView.getText().toString().toLowerCase()).equals("santi")){
ok

2017-04-14 17:38 UTC, chacaa commented on app/src/main/res/layout/login_register_fragment.xml
> +</RelativeLayout>
done!

2017-04-14 17:40 UTC, michaelEllisUy commented on app/src/main/java/com/xmartlabs/daydreaming/ui/LoginRegisterFragment.java
> +        errorTextView.setText("Wrong user account");
Add a TODO explaining that.

2017-04-14 17:40 UTC, michaelEllisUy approved these changes

2017-04-14 19:17 UTC, merged